# Generated by Django 5.0.3 on 2024-05-30 16:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='buyers',
            field=models.ManyToManyField(related_name='purchased_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='khuyen_mai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='home.sanpham')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sanpham', 'user')},
            },
        ),
    ]
